services:
  postgresql:
    image: bitnami/postgresql
    env_file:
      - .env
    ports:
      - '5433:5432'
    # environment:
    #   - POSTGRES_USER:
    #   - POSTGRES_PASSWORD:
    #   - POSTGRES_DB:
    # volumes:
    #   - postgres_data: /bitnami/postgresql
    # networks:
    #   - app_network
    restart: no
